In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
### Vocabulary size
voc_size=10000

In [6]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[6090, 2524, 6622, 1566], [6090, 2524, 6622, 6012], [6090, 3109, 6622, 7899], [38, 7911, 5989, 1441, 4656], [38, 7911, 5989, 1441, 1666], [9737, 6090, 5746, 6622, 6019], [4428, 5771, 3123, 1441]]


In [7]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)#padding adds zero to make same length #pre=starting
print(embedded_docs)

[[   0    0    0    0 6090 2524 6622 1566]
 [   0    0    0    0 6090 2524 6622 6012]
 [   0    0    0    0 6090 3109 6622 7899]
 [   0    0    0   38 7911 5989 1441 4656]
 [   0    0    0   38 7911 5989 1441 1666]
 [   0    0    0 9737 6090 5746 6622 6019]
 [   0    0    0    0 4428 5771 3123 1441]]


In [10]:
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [12]:
model.summary()


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [13]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 218ms/step
[[[ 0.03969569 -0.00539307  0.02960769  0.03971184 -0.00488641
    0.01151899 -0.00821978  0.02126995  0.04051653  0.01128095]
  [ 0.03969569 -0.00539307  0.02960769  0.03971184 -0.00488641
    0.01151899 -0.00821978  0.02126995  0.04051653  0.01128095]
  [ 0.03969569 -0.00539307  0.02960769  0.03971184 -0.00488641
    0.01151899 -0.00821978  0.02126995  0.04051653  0.01128095]
  [ 0.03969569 -0.00539307  0.02960769  0.03971184 -0.00488641
    0.01151899 -0.00821978  0.02126995  0.04051653  0.01128095]
  [-0.03789411  0.04516411 -0.03791652 -0.02545352 -0.009348
    0.00054046  0.02677338  0.0498387   0.04929442  0.02295679]
  [ 0.01722015 -0.0295206  -0.03194914  0.01891707 -0.02636527
   -0.04552802  0.01778742  0.00887177 -0.02848735  0.03882812]
  [ 0.0086296   0.02697236  0.00621488 -0.02841121  0.03936963
   -0.02954007 -0.00375002  0.02988179  0.02359195 -0.00774167]
  [ 0.00192336 -0.0150122   0.03358937 -0.02981762 -0.031997

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 6090, 2524, 6622, 1566], dtype=int32)

In [15]:
print(model.predict(embedded_docs)[0])

1/1 [==============================] - 0s 26ms/step
[[ 0.03969569 -0.00539307  0.02960769  0.03971184 -0.00488641  0.01151899
  -0.00821978  0.02126995  0.04051653  0.01128095]
 [ 0.03969569 -0.00539307  0.02960769  0.03971184 -0.00488641  0.01151899
  -0.00821978  0.02126995  0.04051653  0.01128095]
 [ 0.03969569 -0.00539307  0.02960769  0.03971184 -0.00488641  0.01151899
  -0.00821978  0.02126995  0.04051653  0.01128095]
 [ 0.03969569 -0.00539307  0.02960769  0.03971184 -0.00488641  0.01151899
  -0.00821978  0.02126995  0.04051653  0.01128095]
 [-0.03789411  0.04516411 -0.03791652 -0.02545352 -0.009348    0.00054046
   0.02677338  0.0498387   0.04929442  0.02295679]
 [ 0.01722015 -0.0295206  -0.03194914  0.01891707 -0.02636527 -0.04552802
   0.01778742  0.00887177 -0.02848735  0.03882812]
 [ 0.0086296   0.02697236  0.00621488 -0.02841121  0.03936963 -0.02954007
  -0.00375002  0.02988179  0.02359195 -0.00774167]
 [ 0.00192336 -0.0150122   0.03358937 -0.02981762 -0.03199764  0.03378451